name: Deploy Doxygen Documentation to GitHub Pages

on:
  push:
    branches:
      - master  # 워크플로우가 master 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest  # 가장 최신의 Ubuntu 러너 사용

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # 코드 체크아웃

      - name: Setup Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz  # Doxygen과 Graphviz 설치

      - name: Generate Doxygen documentation
        run: doxygen Apollo.Doxyfile  # Doxygen 실행

      - name: Prepare files for deployment
        run: |
          touch Apollo.Docs/html/.nojekyll  # .nojekyll 파일 생성
          echo "Deploying to GitHub Pages"  # 배포 로그 출력

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # GitHub Pages 배포 액션
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 토큰 사용
          publish_dir: ./Apollo.Docs/html  # 배포할 디렉토리 지정
