name: Deploy Doxygen to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        run: doxygen Apollo.Doxyfile

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          rsync -av --delete Documents/html/ gh-pages/
          cd gh-pages
          touch .nojekyll
          git add .
          git commit -m 'Deploy Doxygen docs'
          git push origin gh-pages
